# Generated by Django 3.2.25 on 2024-05-02 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0003_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyelidr',
            name='StatusACLS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusACRS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusCONJUNCTIVALS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusCONJUNCTIVARS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusCORNEALS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusCORNEARS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusEYELIDLS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusIRISLS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusIRISRS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusLENSLS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusLENSRS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusPUPILLS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusPUPILRS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusRETINALS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusRETINARS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusVITREOUSLS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eyelidr',
            name='StatusVITREOUSRS',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
